name: Shorebird Release
description: Create a new release using the Shorebird CLI

branding:
  icon: package
  color: green

inputs:
  args:
    description: The arguments to pass to the Shorebird release command
    required: false
    default: ""
  flutter-version:
    description: The version of Flutter to use for the release. Use "latest" to always target the latest stable version.
    required: true
  platform:
    description: The platform for which to create a release (e.g. android, ios)
    required: true
  working-directory:
    description: The working directory in which to run Shorebird
    required: false
    default: .

outputs:
  release-version:
    description: The version of the release that was created.
    value: ${{ steps.shorebird-release.outputs.release-version }}

runs:
  using: composite
  steps:
    - name: ðŸ¦ Shorebird Release
      shell: bash
      id: shorebird-release
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail

        # Sanitize args:
        # - YAML literal blocks (`|`) preserve newlines, which would break piping.
        # - Replace newlines with spaces and trim leading/trailing whitespace.
        ARGS='${{ inputs.args }}'
        if [[ "$ARGS" == *$'\n'* ]]; then
          echo "::warning::inputs.args contains newlines; converting them to spaces. Consider using YAML '>-'."
        fi
        ARGS="${ARGS//$'\n'/ }"
        ARGS="$(echo "$ARGS" | awk '{$1=$1; print}')"

        shorebird release '${{ inputs.platform }}' \
          --flutter-version '${{ inputs.flutter-version }}' \
          $ARGS \
          | tee output.log

        GREP_MATCH="$(grep -Ei "Published Release (.*)" output.log || true)"
        if [[ -n "$GREP_MATCH" ]]; then
          # Strip the non-version-number characters from the line
          RELEASE_VERSION="$(echo "$GREP_MATCH" | sed -E 's/^.+ Published Release (.*)\!$/\1/')"
          echo "release-version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
        else
          echo "Failed to create release"
          exit 1
        fi
