name: Shorebird Release
description: Create a new release using the Shorebird CLI

branding:
  icon: package
  color: green

inputs:
  platform:
    description: The platform for which to create a release (e.g. android, ios-alpha)
    required: true
  working-directory:
    description: The working directory in which to run Shorebird
    required: false
    default: .

outputs:
  release-version:
    description: The version of the release that was created.
    value: ${{ steps.shorebird-release.outputs.release-version }}

runs:
  using: composite
  steps:
    - name: ðŸ¦ Shorebird Release
      shell: bash
      id: shorebird-release
      working-directory: ${{ inputs.working-directory }}
      run: |
        OUTPUT=$(shorebird release ${{ inputs.platform }})
        REGEXP="Published Release (.*)!"
        if [[ $OUTPUT =~ $REGEXP ]]; then
        RELEASE_VERSION=${BASH_REMATCH[1]}
        echo "release-version=$(echo $RELEASE_VERSION)" >> $GITHUB_OUTPUT
        else
        echo "Failed to create release"
        exit 1
        fi
